name: deploy/prod

on:
  push:
    branches:
      - release/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.9.0

      - name: Log in to DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script_stop: true
          script: |
            cd test-yagi
            git fetch --tags
            git branch -D test/workflow
            git checkout develop
            git pull
            git checkout -b test/workflow
            echo "${{ secrets.ENVIRONMENT_PROD }}" > src/config/environment.ts
            echo "${{ secrets.DATABASE_PROD }}" > src/config/database.ts
            echo "${{ secrets.CA_CERTIFICATE }}" > src/config/ca-certificate.cer
            yarn install 
            yarn build
            yarn node dist/yagi.js
